# Config file for automatic testing at travis-ci.org

language: python

env:
  - CI=true

python:
  - "3.5"
  - "3.4"
  - "2.7"

before_install:
  - pip install --upgrade codecov
  - mv .env.travis .env

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install --upgrade -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source django_remote_submission -m py.test --ci

after_success:
  - codecov
